files:
  - source: /app/src/main/res/values/strings*.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
    languages_mapping:
      android_code:
        es-ES: es       # Espanol
        de: de          # German
        ru: ru          # Russian
        pl: pl          # Polish
        ja: ja          # Japanese
        it: it          # Italian
        fr: fr          # French
        nl: nl          # Dutch
        hu: hu          # Hungarian
        cs: cs          # Czech
        da: da          # Danish
        sr: sr          # Serbian (Cyrillic)
        pt-PT: pt       # Portugese
        pt-BR: pt-rBR   # Portugese (Brazilian)
        zh-CN: zh-rCN   # Chinese (Simplified)
        sc: sc          # Sardinian
        kab: kab        # Kabyle
#       hi: hi          # Hindi
#       el: el          # Greel
#       "no": 'no'      # Norwegian
#       tr: tr          # Turkish
#       ca: ca          # Catalan
