files:
  - source: /app/src/main/res/values/strings*.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
    languages_mapping:
      android_code:
        es-ES: es
        de: de
        ru: ru
        pl: pl
        ja: ja
        it: it
        fr: fr
        nl: nl
        hu: hu
        cs: cs
        da: da
        sr: sr
        pt-PT: pt
        pt-BR: pt-rBR
        zh-CN: zh-rCN
        sc: sc
        kab: kab
